Update drive-health-monitor
Fixed singleton check

diff --git a/drive-health-monitor b/drive-health-monitor
--- a/drive-health-monitor
+++ b/drive-health-monitor
@@ -23,16 +23,6 @@ xfsdrives="/dev/xfshdd1 /dev/xfshdd2" # These are any XFS formatted spinning dis
 set -euo pipefail
 shopt -s nullglob
 
-# Ensure this is the only running instance, if otherwise bail
-for pid in $(pgrep -f "$(basename "$0")"); do
-  if [ "$pid" != "$$" ]; then
-    echo "To ensure data integrity, only 1 instance of this drive health monitor can be run at a time"
-    echo "There is already a currently running instance of this drive health monitor"
-    echo "I will exit"
-    exit 1
-  fi
-done
-
 # Check if runnning as full root (vs as user, or even with sudo)
 # Must be real root, not sudo
 notroot="ERROR: This script must be run as FULL ROOT"
@@ -80,6 +70,7 @@ wayland=0
 mountbase="${mountbase%$'\n'}"
 offline_gui_alert_dir="/usr/local/bin/drive-health-monitor-user_alert"
 offline_profile_alert="/etc/profile.d/drive-health-alert.sh"
+tmp="${TMPDIR:-/tmp}"
 
 if [ "${testmode}" == "1" ] ; then
   ## TEST Mode
@@ -114,6 +105,26 @@ else
   alert_email_header3="-C X-MSMail-Priority:High"
   alert_email_header4="-C Importance:High"
 fi
+
+# Lock file path
+lockfile="${tmp}/.lock.drive-health-monitor"
+
+# Open FD 9 (exit if this fails)
+exec 9>"$lockfile" || {
+  echo "Unable to create lockfile"
+  echo "Assuming drive error!"
+  smartctltest="LOCKFILE_ERROR"
+  alert_email_header1="-C drive-health-monitor-status:LOCKFILE_ERROR"
+  testheader="\n  !LOCK FILE CREATION ERROR! \n"
+}
+
+# Try non-blocking lock (exit if already locked)
+flock -n 9 || {
+  echo "To ensure data integrity, only 1 instance of this drive health monitor can be run at a time"
+  echo "There is already a currently running instance of this drive health monitor"
+  echo "I will exit"
+  exit 1
+}
 
 # Detect any Wayland sessions
 for de in $(loginctl list-sessions --no-legend | awk '{print $1}'); do
